### PR TITLE
Fixed gulp-rename order in pipeline

### PR DESCRIPTION
**Pull request by liqueflies**
Resolved issue #32 changing the rename order in the pipeline.

### CODE REVIEW

**Comment by kino90** [comment]
Cool! Thanks a lot @liqueflies ! Watch out for `console.log`s 😉

**Comment by liqueflies** [comment]
Done :)

**Comment by kino90** [comment]
Thanks again @liqueflies ! :wink: Let's wait @dwightjack for the merge!

**Comment by dwightjack** [comment]
Great! @liqueflies thank you for your contribution!

**Pull request merged**
